### ISSUE TITLE
riscv_application_profiler: command not found

### ISSUE THREAD

**Issue by chuanyuL** [mahendraVamshi/riscv-application-profiler#30]
Hi,thank you for the useful solution for riskv profiler.But I get the Q:riscv_application_profiler: command not found when I write the conde:riscv_application_profiler --help. I will give my great appreciation if you can give me some suggestions.

**Comment by mahendraVamshi** [comment]
Hi, are you sure you have followed the installation steps mentioned in the readme 
 If not, here are the steps, you copy past all the commands at once in your terminal and then try using it:
`git clone https://github.com/mahendraVamshi/pycachesim.git`
`cd pycachesim`
`pip install -e .`
`cd ..`
`git clone https://github.com/mahendraVamshi/riscv-isac.git`
`cd riscv-isac`
`pip install -e .`
`cd ..`
`git clone https://github.com/mahendraVamshi/riscv-application-profiler.git`
`cd riscv-application-profiler`
`pip install -e .`

After completion of above, you can run `riscv_application_profiler --help` command on the terminal
